name: projects
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  http: ^0.13.4
  responsive_framework: ^0.1.5
  image_picker: ^0.8.4+5
  flutter_spinkit: ^5.1.0
  permission_handler: ^8.3.0
  cached_network_image: ^3.2.0
  get_storage: ^2.0.3
  font_awesome_flutter: ^9.2.0
  connectivity: ^3.0.6
  story: ^0.6.0
  photo_gallery: ^1.1.1
  transparent_image: ^2.0.0
  video_player: ^2.2.18
#  sentry_flutter: ^6.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.4


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/



  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
